### ISSUE TITLE
Moveit_python in namespaced node does not place the topics in the namespace

### ISSUE THREAD

**Issue by BasJ93** [mikeferguson/moveit_python#12]
I wrote a ROS node that uses both the PlanningSceneInterface and the RobotCommander. The node works as expected when my robot is not namespaced, but since I want to use multiple arms I need to be able to namespace the robots. As soon as I do this, the PlanningSceneInterface does not map its topics to the namespaced topics created by move_group. The RobotCommander does work as expected.

In your code I see no reason the topics should not end up in the namespace as they don't have a leading slash, but somehow the do not. Can you help me out?

**Comment by mikeferguson** [comment]
I'm not sure what "RobotCommander" is -- we don't have a class like that in this code. I think #16 will add the PlanningSceneInterface mappings needed.
