### ISSUE TITLE
"from pyassimp import pyassimp" in planning_scene_interface.py is correct?

### ISSUE THREAD

**Issue by raucha** [mikeferguson/moveit_python#13]
Hello 
Acording to pyassimp's [README.md](https://github.com/assimp/assimp/tree/master/port/PyAssimp), 
I think 
` import pyassimp` 
is correct rather than "from pyassimp import pyassimp" at line 31 in planning_scene_interface.py.

I've failed launching Moveit! while trying [fetch robot demo](http://docs.fetchrobotics.com/gazebo.html) and get below error
```
☁  ~  roslaunch fetch_gazebo_demo demo.launch
... 
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://E440:40788/
.
.
.
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/fetch_gazebo_demo/demo.py", line 36, in <module>
    from moveit_python import (MoveGroupInterface,
  File "/opt/ros/indigo/lib/python2.7/dist-packages/moveit_python/__init__.py", line 4, in <module>
    from planning_scene_interface import PlanningSceneInterface
  File "/opt/ros/indigo/lib/python2.7/dist-packages/moveit_python/planning_scene_interface.py", line 31, in <module>
    from pyassimp import pyassimp
ImportError: cannot import name pyassimp
[demo-7] process has died [pid 9461, exit code 1, cmd /opt/ros/indigo/lib/fetch_gazebo_demo/demo.py __name:=demo __log:=/hom
```
And changing ` from pyassimp import pyassimp` to ` import pyassimp` make demo work correctly.
But this line hasn't been edited long time and I don't know why it worked at past time.
my pyassimp version is 3.3
```
☁  ~  pip freeze | grep pyassimp
pyassimp==3.3
```
Sorry for my poor English 
Thank you

**Comment by mikeferguson** [comment]
So:
 * Trusty has 3.0 in debs -- https://packages.ubuntu.com/trusty/python-pyassimp. This is definitely tested with Indigo.
 * Xenial has 3.2 in debs -- which is definitely broken (see https://github.com/mikeferguson/moveit_python/issues/8)

It's certainly possible that this is needed. I have recently moved to Melodic+Bionic (which has 4.1), but haven't gotten a chance to test items this high in my ROS stack. 

I'd recommend uninstalling the pip version and installing the debian version of pyassimp if you are on Trusty+Indigo.

**Comment by mikeferguson** [comment]
I believe this is fixed in https://github.com/mikeferguson/moveit_python/commit/411e26a354dee7e439b004ad17d16012e9a3f1a9
