### ISSUE TITLE
ObjectManager: sync timed out.

### ISSUE THREAD

**Issue by weihaosky** [mikeferguson/moveit_python#14]
Hi, 
I always get the error "ObjectManager: sync timed out." when I use p.addCube("my_cube", 0.1, 1, 0, 0.5)
What is the problem?

**Comment by mikeferguson** [comment]
There could be any number of problems here -- there isn't nearly enough information here to debug the issue. I would suggest posting a more detailed issue on answers.ros.org (which robot, which version of ROS, which version of Ubuntu, etc)
