### ISSUE TITLE
Update the planning scene wrapper with namespace functionality.

### ISSUE THREAD

**Issue by Benjamin-Tan** [mikeferguson/moveit_python#15]
Hi, this package provides a better python binding than the official moveit_commander python package. However, I found a need to use the planning scene with specific **namespace**, which is not really well supported even with the official moveit_commander package. Therefore, I have modify your source code on _planning_scene_interface.py_ slightly with the following. This is to incorporate multiple planning scene for different robot namespace (e.g. robot1/planning_scene or robot2/planning_scene). I find that this merge could be helpful for those who are going to use this functionality. 

`
class PlanningSceneInterface(object):
    def __init__(self, frame, ns='', init_from_service=True):
        # ns must be a string
        if not isinstance(ns,basestring):
            rospy.logerr('Namespace must be a string!')

        self._fixed_frame = frame

        # publisher to send objects to MoveIt
        self._pub = rospy.Publisher(ns + '/collision_object',
                                    CollisionObject,
                                    queue_size=10)
        self._attached_pub = rospy.Publisher(ns + '/attached_collision_object',
                                             AttachedCollisionObject,
                                             queue_size=10)
        self._scene_pub = rospy.Publisher(ns + '/planning_scene',
                                          PlanningScene,
                                          queue_size=10)

        # track the attached and collision objects
        self._mutex = thread.allocate_lock()
        # these are updated based what the planning scene actually contains
        self._attached = list()
        self._collision = list()
        # these are updated based on internal state
        self._objects = dict()
        self._attached_objects = dict()
        self._removed = dict()
        self._attached_removed = dict()
        self._colors = dict()

        # get the initial planning scene
        if init_from_service:
            rospy.loginfo('Waiting for get_planning_scene')
            rospy.wait_for_service(ns + '/get_planning_scene')
            self._service = rospy.ServiceProxy(ns + '/get_planning_scene',
                                               GetPlanningScene)
            try:
                req = PlanningSceneComponents()
                req.components = sum([
                    PlanningSceneComponents.WORLD_OBJECT_NAMES,
                    PlanningSceneComponents.WORLD_OBJECT_GEOMETRY,
                    PlanningSceneComponents.ROBOT_STATE_ATTACHED_OBJECTS])
                scene = self._service(req)
                self.sceneCb(scene.scene, initial=True)
            except rospy.ServiceException as e:
                rospy.logerr('Failed to get initial planning scene, results may be wonky: %s', e)

        # subscribe to planning scene
        rospy.Subscriber(ns + '/move_group/monitored_planning_scene',
                         PlanningScene,
                         self.sceneCb)
`

**Comment by mikeferguson** [comment]
Please open a pull request for discussion -- it's much easier to look at the actual changes in Github's PR view. Thanks!
