### ISSUE TITLE
How to set "is_diff" in this package

### ISSUE THREAD

**Issue by Hubert51** [mikeferguson/moveit_python#19]
I try to use removeAttachedObject() function to remove the attached object. But the terminal gives me this error. 
`The specified RobotState is not marked as is_diff. The request to modify the object 'microwave_door1' is not supported. Object is ignored`

Where can I set this flag? 

Thank you!

**Comment by mikeferguson** [comment]
I'm not sure how this is happening, because RemoveAttachedObject() uses sendUpdate(), which sets is_diff to True here: https://github.com/mikeferguson/moveit_python/blob/master/src/moveit_python/planning_scene_interface.py#L111
